version: '3.2'

services:
  movie:
    build: 
      context: movieService/
    stdin_open: true
    tty: true
    restart: always
    environment:
    - DEBUG=1
    - server.port=8080
    ports:
    - "8080"

  actor:
    build: 
      context: actorService/
    stdin_open: true
    tty: true
    restart: always
    links:
      - "movie:movieService"
    environment:
    - DEBUG=1
    - movieService=movieService:8080    
    - server.port=80
    ports:
      - "80:80"

