version: '3.2'

services:
  movie:
    build: 
      context: movieService/
    ports:
      - "8080"
    stdin_open: true
    tty: true
    restart: always
    links:
      - movie

  actor:
    build: 
      context: actorService/
    stdin_open: true
    tty: true
    restart: always

networks: 
  backend:
  frontend:
