version: '3.9'

services:
  movie:
    build: 
      context: movieService/
    image: ghcr.io/iamfrench/efrei-m2-st2dccc_movie
    stdin_open: true
    tty: true
    environment:
    - DEBUG=1
    - server.port=8080
    ports:
    - "82:8080"
    deploy:
      replicas: 1

  actor:
    build: 
      context: actorService/
    image: ghcr.io/iamfrench/efrei-m2-st2dccc_actor
    stdin_open: true
    tty: true
    environment:
    - DEBUG=1
    - movieService=movie:8080 # This is the DNS + port of the movie service
    - server.port=80
    ports:
      - "81:80"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip

  swagger:
    image: swaggerapi/swagger-ui
    stdin_open: true
    tty: true
    environment:
      - SWAGGER_JSON=/tmp/swagger.yaml
    volumes:
      - ./swagger.yaml:/tmp/swagger.yaml
    ports:
      - "80:8080"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
