swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Movie Actor Service"
  # termsOfService: "http://swagger.io/terms/"
  contact:
    email: "alexandre.pares-breton@efrei.net"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

host: "localhost:81"
basePath: "/"

tags:
- name: "Movies"
  description: "Everything about your movies"
schemes:
- "http"
paths:
  /findAll:
    get:
      tags:
      - "Movies"
      summary: "List all movies"
      description: ""
      operationId: "getMovies"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 OK"
          schema:
            type: array
            items:
              $ref: '#/definitions/movie'
          
  /findOne/{movieId}:
    get:
      tags:
      - "Movies"
      summary: "Display informations about a single movie"
      description: ""
      operationId: "getMovie"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "movieId"
        in: "path"
        description: "ID of movie to display"
        required: true
        type: "integer"
        format: "int64"
      - name: "delay"
        in: "query"
        type: "integer"
        description: "Delay to be added to the query, if this number is over 500 (ms) the actor service will fallback to a default response"
        required: false
      responses:
        "200":
          description: "200 OK"
          schema:
            $ref: '#/definitions/movie'
definitions:
  movie:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      description:
        type: "string"
      actors:
        type: "string"