swagger: "2.0"
info:
  description: "This interface allows you to play with our project. This project is composed of 2 micro-services: 1. The movie services, that list movies and 2. The actor service that act as a proxy to the movie service and add to the requested movie additionals infomations about actors that have played in a specific movie."
  version: "1.0.0"
  title: "Swagger Movie Actor Service"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

host: "localhost:81"
basePath: "/"

tags:
- name: "Movies"
  description: "Everything about your movies"
schemes:
- "http"
paths:
  /findAll:
    get:
      tags:
      - "Movies"
      summary: "List all movies"
      description: ""
      operationId: "getMovies"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        "200":
          description: "200 OK"
          schema:
            type: array
            items:
              $ref: '#/definitions/movie'
          
  /findOne/{movieId}:
    get:
      tags:
      - "Movies"
      summary: "Display informations about a single movie"
      description: ""
      operationId: "getMovie"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "movieId"
        in: "path"
        description: "ID of movie to display"
        required: true
        type: "integer"
        format: "int64"
      - name: "delay"
        in: "query"
        type: "integer"
        description: "Delay to be added to the query, if this number is over 500 (ms) the actor service will fallback to a default response"
        required: false
      responses:
        "200":
          description: "200 OK"
          schema:
            $ref: '#/definitions/movie'
definitions:
  movie:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      description:
        type: "string"
      actors:
        type: "string"